---
- hosts: webservers 
  become: True
  tasks:
    - name: Install apache2
      apt:
        name: "apache2"
        state: "present"
    - name: Start Apache server
      service:
        name: apache2
        state: started
        enabled: True
 ...
